version: '2'
services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT:3306"
      - "DB_HOST:mysql"
  nginx:
    image: nginx:1.13.12
    working_dir: /var/www
    volumes:
      - ./docker/host.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    ports:
      - "33061:3306"
volumes:
  dbdata: